version: "3.8"
services:
    msbienalive:
       image: img-msbienalive
       container_name: ms-bienalive
       restart: always
       environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - TZ=America/Bogota
       ports:
        - "80:80"